eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8876
spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:oracle:thin:@10.1.1.173:1521:sales
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: greescmdb2
    password: geli*scm_10142015
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false

security:
  oauth2:
#    client:
#      client-id: client3
#      client-secret: 123456
#      access-token-uri: http://localhost:9091/oauth/token
#      user-authorization-uri: http://localhost:9091/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:9091/users/current
        key-value: internet_plus
