server:
  port: 8087
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: rabbitstream-licence
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: hints
                password: hints
      bindings:
        inchannel:
          destination: orgChangeTopic
          content-type: application/json
          binder: rabbitmq
