test:
  uri: lb://eurka-serverB

spring:
  profiles:
    active: route_service_one

#在application.yml再建一个配置文件，语法是三个横线
---
spring:
  application:
    name: gateway-client
  redis:
    host: 127.0.0.1
    database: 1
  cloud:
    gateway:
      routes:
      #      - id: route_service_one
      #        uri: http://localhost:8081
      #        predicates:
      #        - Path=/user/who
      - id: route_service_one
        uri: ${test.uri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
        predicates:
#        - After=2020-01-20T17:42:47.789-07:00[America/Denver]
        - Path=/order/**
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}' #使用SPEL表达式从spring容器中获取bean容器
            redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
            redis-rate-limiter.burstCapacity: 2 #令牌桶的总容量

      - id: userapi2_route
        uri: ${test.uri}
        predicates:
        - Path=/userapi2/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: myfallbackcmd
            fallbackUri: forward:/user/fallback


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true # 是否启用注册服务 默认为true, false是不启用
  instance:
    prefer-ip-address: true