server:
  port: 9007

spring:
  application:
    name: configmess2
  cloud:
    config:
      fail-fast: true
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: hints
    password: hints

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: bus-refresh
