eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:oracle:thin:@10.2.25.244:1521/greeprotest
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: pro
    password: greepro2014
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false

